# Generated by Django 5.1.4 on 2025-04-16 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLoan',
            fields=[
                ('loan_amount', models.IntegerField()),
                ('loan_date', models.DateField()),
                ('loan_period', models.CharField(choices=[('1M', '1M'), ('3M', '3M'), ('6M', '6M'), ('12M', '12M')], max_length=4)),
                ('loan_reason', models.CharField(max_length=200)),
                ('is_approved', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)])),
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_manager.memployee')),
            ],
            options={
                'db_table': 't_loan',
                'managed': True,
            },
        ),
    ]
