# Generated by Django 5.1.4 on 2025-04-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_manager', '0002_tloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tloan',
            old_name='leave_id',
            new_name='loan_id',
        ),
    ]
